# Generated by Django 4.2.5 on 2023-09-11 13:35

import Fruitipedia_App.my_app_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), Fruitipedia_App.validators.validate_starts_with_letter])),
                ('lat_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1), Fruitipedia_App.validators.validate_starts_with_letter])),
                ('email', models.EmailField(blank=True, max_length=40)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
    ]
